version: '3.9'
services:

  server:
    build:
      context: server
    stop_signal: SIGKILL
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:admin@db:5432/junior_twitter_clone
      - SAVE_MEDIA_PATH=/usr/share/nginx/html/images
    networks:
      - junior_twitter_clone
    ports:
      - '80:80'
    volumes:
      - ./server/static/images:/usr/share/nginx/html/images
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    stop_signal: SIGKILL
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=junior_twitter_clone
    networks:
      - junior_twitter_clone
    ports:
      - '5432:5432'
    volumes:
      - ./db_data/:/var/lib/postgresql/data
    command: >
      postgres -c listen_addresses='*' 
               -c log_destination=stderr 
               -c logging_collector=on 
               -c log_directory=/var/lib/postgresql/data/log

networks:
  junior_twitter_clone:
    driver: bridge