version: '3.9'
services:

  server:
    build:
      context: server
    stop_signal: SIGKILL
    env_file:
      - ./.env
    networks:
      - junior_twitter_clone
    ports:
      - '80:80'
    volumes:
      - ./server/static/images:/usr/share/nginx/html/images
      - ./logs/app/:${LOGS_PATH}
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    stop_signal: SIGKILL
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - junior_twitter_clone
    ports:
      - '5432:5432'
    volumes:
      - ./db_data/:/var/lib/postgresql/data
    command: >
      postgres -c listen_addresses='*' 
               -c log_destination=stderr 
               -c logging_collector=on 
               -c log_directory=/var/lib/postgresql/data/log

networks:
  junior_twitter_clone:
    driver: bridge