FROM python:3.10

RUN apt-get update && apt-get install -y python3-dev supervisor nginx && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/
RUN pip install -r /app/requirements.txt

COPY app/ /app/
COPY nginx.conf /etc/nginx/nginx.conf
COPY ./static /usr/share/nginx/html
COPY supervisord.ini /etc/supervisor/conf.d/supervisord.ini


WORKDIR /app

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.ini"]